# Site settings
title: Katie Shepherd
email: kshepherd@media.ucla.edu
phone_number: 858-254-7242
description: "Student journalist covering higher education and campus politics."
baseurl: ""
url: "/" 
twitter_username: katemshepherd
blog_desc: "Follow me through my reporting process and learn about my life as a student journalist."
folio_desc: "Below is a list of featured clips from my experience as a journalist."
paginate: 7
photo: /img/prof-pic.jpg
favicon: "/favicon.io"
# Build settings
markdown: kramdown