# Site settings
title: Katie Shepherd
email: kms2272@columbia.edu
description: "Journalist interested in the intersections between politics, religion and government actions"
baseurl: ""
url: http://katiemshepherd.com
twitter_username: katemshepherd
favicon: "favicon.ico"
# Build settings
markdown: kramdown
