# Site settings
title: Katie Shepherd
email: katie.shepherd@latimes.com
phone_number: 858-254-7242
description: "Los Angeles Times intern covering national news."
baseurl: ""
url: "/" 
twitter_username: katemshepherd
blog_desc: "Follow me through my reporting process and learn about my life as a student journalist."
folio_desc: "Below is a list of featured clips from my experience as a journalist."
paginate: 7
photo: /img/profpic.jpg
favicon: "/favicon.io"
# Build settings
markdown: kramdown